### ISSUE TITLE
.mailmap file seems incomplete

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [mozilla/gecko#5]
The following command returns author and commiter email ids instead of their names. The .mailmap file contains only three entries.  

Command from python. 
git.log('--pretty=%H %an %cn %s','--before=some_date',filename)

Output
677cdde6477cc92b7779d4239df66d6c8ced7aba
bienvenu%nventure.com
bienvenu%nventure.com
fix 103732, sending unsent messages doesn't set replied/forwarded status on original msg, r/sr=mscott

**Comment by mykmelez** [comment]
@HEMA-MATHAVAN This repository is just a mirror of the [mozilla-central repository](https://hg.mozilla.org/mozilla-central/), and any issues that you experience when using GitPython with it are likely due to GitPython itself, not this repository.

I see that you also filed https://github.com/gitpython-developers/GitPython/issues/863 on this issue. I'd follow up there with additional details that allow its developers to reproduce your problem.
